spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    
  datasource: 
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_reteev_kdh01?serverTimezone=UTC&characterEncoding=UTF-8
    username: practice
    password: 1234
    hikari:
      auto-commit: false
      connection-timeout: 30000
      keepalive-time: 0
      maximum-pool-size: 10
      

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true

server:
  error:
    include-message: always